#!/bin/bash
# -*- mode: shell-script; mode: flyspell-prog; -*-

# target
target=$(uname)

# install prefix
prefix=/opt/tinyos

# tinyos
repo_tinyos=:pserver:anonymous@tinyos.cvs.sourceforge.net:/cvsroot/tinyos
tinyos=tinyos-2.x

# nesc
url_nesc=http://softlayer.dl.sourceforge.net/project/nescc/nescc/v1.3.1
nesc=nesc-1.3.1

# stow
repo_stow=git://git.savannah.gnu.org/stow.git

# Local Variables:
# indent-tabs-mode: nil
# End:
# vim: set et ts=4 sw=4:
